eureka:
  instance:
    ## 向Eureka 服务端发送心跳的间隔时间，单位为秒，用于服务续约。这里配置为20秒，即每隔20秒向febs-register发送心跳，表明当前服务没有宕机
    lease-renewal-interval-in-seconds: 20
  client:
    ## 为true时表示将当前服务注册到Eureak服务端
    register-with-eureka: true
    ## 为true时表示从Eureka 服务端获取注册的服务信息
    fetch-registry: true
    ## 新实例信息的变化到Eureka服务端的间隔时间，单位为秒
    instance-info-replication-interval-seconds: 30
    ## 默认值为30秒，即每30秒去Eureka服务端上获取服务并缓存，这里指定为3秒的原因是方便开发时测试，实际可以指定为默认值即可
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://cloud:123456@localhost:8001/register/eureka/